name: Deploy to Beget via FTP

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: weather-app

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '23'

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Generate API keys
              env:
                  API_KEY_IP: ${{ secrets.API_KEY_IP }}
                  API_KEY_TIME: ${{ secrets.API_KEY_TIME }}
              run: node generateApiKeys.js

            - name: FTP Deploy
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ftp://ftp.your-beget-domain.com
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  protocol: ftps
                  local-dir: ./
